school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('www.urls')),
    path('', include('schedule.urls')),
    path('', include('admin_panel.urls'))
]

www/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
        path('', home, name='home'),
        path('contact/', contact, name='contact'),
        path('documents/', documents, name='documents'),
        path('news/', NewsListView.as_view(), name='news'),
        path('news/<int:pk>/', news_details.as_view(), name='news_details'),
        path('info/', school_info, name='info'),
        path('svedeniya/', organization_info, name='organization_info'),
        path('structure', structure, name='structure'),
        path('education', education, name='education'),
        path('standart', standart, name='standart'),
        path('material_support', material_support, name='material_support'),
        path('financial', financial, name='financial'),
        path('first-grade-admission/', first_grade_admission, name='first_grade_admission'),
        path('clubs-and-sections/', clubs_and_sections, name='clubs_and_sections'),
        path('rucovodstvo/', staff, name='staff'),
        path('vospitatelnaya-rabota/', educational_work, name='educational_work'),
        path('food-monitoring/', food_monitoring, name='food_monitoring'),
        path('quality-assessment/', quality_assessment, name='quality_assessment'),
        path('scholarships/', scholarships, name='scholarships'),
        path('paid-services/', paid_services, name='paid_services'),
        path('international/', international, name='international'),
        path('vacant', vacant_places, name='vacant'),
        path('local-acts/', local_acts, name='local_acts'),
        path('contactmessage/<int:pk>/respond/', respond_to_message, name='respond_to_message'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schedule/models.py
from django.db import models
from django.core.exceptions import ValidationError


class Subject(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

class Classroom(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Учебный кабинет'
        verbose_name_plural = 'Учебные кабинеты'
class Class(models.Model):
    name = models.CharField(max_length=50)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Номер класса'
        verbose_name_plural = 'Номер класса'

class Lesson(models.Model):
    class_name = models.ForeignKey(Class, on_delete=models.CASCADE)
    teacher = models.ForeignKey('www.Teacher', on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey('schedule.Subject', on_delete=models.SET_NULL, null=True)
    day_of_week = models.CharField(max_length=10, choices=[
        ('Monday', 'Понедельник'),
        ('Tuesday', 'Вторник'),
        ('Wednesday', 'Среда'),
        ('Thursday', 'Четверг'),
        ('Friday', 'Пятница'),
        ('Saturday', 'Суббота'),
    ])
    lesson_number = models.IntegerField()  # Номер урока (1, 2, 3, ...)

    def clean(self):
        # Проверка на повторение уроков у одного класса в один день
        existing_lessons = Lesson.objects.filter(
            class_name=self.class_name,
            day_of_week=self.day_of_week,
            lesson_number=self.lesson_number,
        ).exclude(id=self.id)  # Исключаем текущий урок при редактировании

        if existing_lessons.exists():
            raise ValidationError(
                f"У класса {self.class_name} уже есть урок в {self.day_of_week} на {self.lesson_number} урок."
            )

        # Проверка на то, что учитель не ведёт урок одновременно в двух классах
        teacher_conflict = Lesson.objects.filter(
            teacher=self.teacher,
            day_of_week=self.day_of_week,
            lesson_number=self.lesson_number,
        ).exclude(id=self.id)

        if teacher_conflict.exists():
            raise ValidationError(
                f"Учитель {self.teacher} уже ведёт урок в {self.day_of_week} на {self.lesson_number} урок."
            )

        # Проверка на то, что кабинет не занят другим классом
        if self.class_name.classroom:
            classroom_conflict = Lesson.objects.filter(
                class_name__classroom=self.class_name.classroom,
                day_of_week=self.day_of_week,
                lesson_number=self.lesson_number,
            ).exclude(id=self.id)

            if classroom_conflict.exists():
                raise ValidationError(
                    f"Кабинет {self.class_name.classroom} уже занят в {self.day_of_week} на {self.lesson_number} урок."
                )

    def save(self, *args, **kwargs):
        self.full_clean()  # Вызов проверок перед сохранением
        super().save(*args, **kwargs)

    def __str__(self):
            return f"{self.class_name} - {self.subject} ({self.teacher})"

    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписание'
class Replacement(models.Model):
    original_lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    new_teacher = models.ForeignKey('www.Teacher', on_delete=models.CASCADE, null=True, blank=True)
    new_subject = models.ForeignKey(Subject, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()  # Дата замены

    def __str__(self):
        return f"Замена для {self.original_lesson} на {self.date}"

    class Meta:
        verbose_name = 'Замена'
        verbose_name_plural = 'Замена'

# Create your models here.

templates/include/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Размахнинская СОШ{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    {% block extra_css %}{% endblock %}


</head>
<body>
<header>

<div class="container-1">
  <div class="menu-overlay" id="menuOverlay" onclick="closeMenu(event)">
    <div class="menu-container" onclick="event.stopPropagation()">
      <button class="close-button" onclick="toggleMenu()">&times;</button>
      <div class="sidebar">
        <ul>
          <li onclick="toggleSubmenu(this)">
            Родителям и ученикам
            <div class="submenu">
              <a href="{% url 'first_grade_admission' %}">Набор в первый класс</a>
              <a href="{% url 'news' %}">Новости</a>
              <a href="{% url 'clubs_and_sections' %}">Секции и кружки</a>
              <a href="{% url 'educational_work' %}">Воспитательная работа</a>
            </div>
          </li>
          <li onclick="toggleSubmenu(this)">
            Наша школа
            <div class="submenu">
              <a href="{% url 'info' %}">Основные сведения</a>
              <a href="{% url 'class_list' %}">Расписание</a>
              <a href="{% url 'staff' %}">Руководство</a>
              <a href="{% url 'material_support' %}">Материально-техническое обеспечение</a>
            </div>
          </li>
          <li onclick="toggleSubmenu(this)">
            Сведения об образовательной организации
            <div class="submenu">
              <a href="{% url 'structure' %}">Структура и органы управления</a>
              <a href="{% url 'education' %}">Образование</a>
              <a href="{% url 'standart' %}">Образовательные стандарты</a>
              <a href="{% url 'staff' %}">Руководство и педагогический состав</a>
              <a href="{% url 'material_support' %}">Материально-техническое обеспечение</a>
              <a href="{% url 'scholarships' %}">Стипендия и меры поддержки</a>
              <a href="{% url 'paid_services' %}">Платные образовательные услуги</a>
              <a href="{% url 'financial' %}">Финансовая-хозяйственная деятельность</a>
              <a href="{% url 'vacant' %}">Вакантные места для приема</a>
              <a href="{% url 'material_support' %}#dostyp">Доступная среда</a>
              <a href="{% url 'international' %}">Международное сотрудничество</a>
            </div>
          </li>
          <li><a href="{% url 'contact' %}">Контакты</a></li>
          <li><a href="{% url 'food_monitoring' %}">Мониторинг питания</a></li>
          <li><a href="{% url 'quality_assessment' %}">Независимая оценка качества</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>





    <div class="container">
        <div class="logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/logo.png' %}" alt="">
                <span>Размахнинская СОШ</span>
            </a>
        </div>
        <nav>
            <div class="mobile-menu-toggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <ul class="nav-menu">
                <li><a href="{% url 'home' %}" class="{% if request.path == '/' %}active{% endif %}">Главная</a></li>
                <li><a href="{% url 'news' %}" class="{% if 'news' in request.path %}active{% endif %}">Новости</a></li>
                <li><a href="{% url 'organization_info' %}" class="{% if 'organization_info' in request.path %}active{% endif %}">Сведения об образовательной организации</a></li>


                <li><a href="{% url 'documents' %}" class="{% if 'documents' in request.path %}active{% endif %}">Документы</a>
                </li>
            </ul>
        </nav>
<button class="menu-button" onclick="toggleMenu()"><span></span>
                <span></span>
                <span></span></button>

{#    <div class="search-container">#}
{#        <form class="search-form" method="get" action="/search">#}
{#            <input class="search-input" type="search" name="search-text" placeholder="Поиск..." />#}
{#            <button class="search-button">#}
{#                <img src="https://cdn-icons-png.flaticon.com/512/622/622669.png" alt="Поиск">#}
{#            </button>#}
{#        </form>#}
{#    </div>#}
{##}


    </div>
</header>

<main>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="message {{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %}{% endblock %}
</main>

<footer>
    <div class="container">
        <div class="footer-grid">
            <div class="footer-about">
                <div class="logo">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'images/logoW.png' %}" alt="Academy High School Logo">
                        <span>МОУ "Размахнинская" СОШ</span>
                    </a>
                </div>


            </div>
            <div class="footer-links">
                <h4>Полезные ссылки</h4>
                <ul>
                    <li><a href="{% url 'info' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Связаться с нами</a></li>
                    <li><a href="{% url 'first_grade_admission' %}">Набор в первый класс</a></li>
                    <li><a href="{% url 'educational_work' %}">Воспитательная работа</a></li>

                    <li><a href="{% url 'local_acts' %}">Локальные акты образовательной организации</a></li>
                </ul>
            </div>

            <div class="footer-contact">
                <h4>Наши контакты</h4>
                <address>
                    <p><i class="icon-map-pin"><img src="{% static 'images/map.svg' %}"></i>с. Размахнино, Школьная ул., 4</p>
                    <p><i class="icon-phone"><img src="{% static 'images/phone.svg' %}"></i> 8 (30244) 31-5-11</p>
                    <p><i class="icon-mail"><img src="{% static 'images/email.svg' %}"></i> razmahnino-sosh2014@mail.ru</p>
                </address>
            </div>
        </div>
        <div class="footer-bottom">
            <p>&copy; {% now "Y" %} Все права защищены.</p>
            <div class="footer-bottom-links">
                <a href="#">Privacy Policy</a>
                <a href="#">Terms of Service</a>
                <a href="#">Accessibility</a>
            </div>
        </div>
    </div>
</footer>
<!-- <script src="https://cdn.userway.org/widget.js" data-account="hbSt8ea7xl"></script> -->
<script src="{% static 'js/main.js' %}"></script>
<script>
    function toggleMenu() {
        var menu = document.getElementById("menuOverlay");
        menu.style.display = (menu.style.display === "flex") ? "none" : "flex";
    }
    function closeMenu(event) {
        var menu = document.getElementById("menuOverlay");
        if (event.target === menu) {
            menu.style.display = "none";
        }
    }

    function showMenu(menuId) {
        // Скрываем все подменю
        document.querySelectorAll('.submenu').forEach(menu => menu.classList.remove('active'));

        // Показываем нужное подменю
        document.getElementById(menuId).classList.add('active');
    }
function toggleSubmenu(element) {
  // Закрыть другие
  document.querySelectorAll('.sidebar li.active').forEach(li => {
    if (li !== element) li.classList.remove('active');
  });
  // Переключить текущее
  element.classList.toggle('active');
}
</script>

<a href="#" onclick="finevision.activate_navbar(); return false;" class="accessibility-button">
    Версия для слабовидящих
</a>
<script src="https://finevision.ru/static/js/finevision_banner.js"></script>

{% block extra_js %}{% endblock %}



</body>
</html>